{"ast":null,"code":"var _jsxFileName = \"/Users/luffyzhou/webfront/github/next-sentry-demo/pages/index.js\";\nimport React from \"react\";\nvar __jsx = React.createElement;\nimport Link from 'next/link';\n\nvar Home = function Home() {\n  return __jsx(\"div\", {\n    style: {\n      maxWidth: 700,\n      margin: '0 auto'\n    },\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 4\n    },\n    __self: this\n  }, __jsx(\"h2\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 5\n    },\n    __self: this\n  }, \"Next-Sentry-Demo\"), __jsx(\"p\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 6\n    },\n    __self: this\n  }, \"This example demonstrates how to record unhandled exceptions in your code with Sentry. There are several test pages below that result in various kinds of unhandled exceptions.\"), __jsx(\"p\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 11\n    },\n    __self: this\n  }, __jsx(\"strong\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 12\n    },\n    __self: this\n  }, \"Important:\"), \" exceptions in development mode take a different path than in production. These tests should be run on a production build (i.e. 'next build').\", ' ', __jsx(\"a\", {\n    href: \"https://nextjs.org/docs#custom-error-handling\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 15\n    },\n    __self: this\n  }, \"Read more\")), __jsx(\"ul\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 17\n    },\n    __self: this\n  }, __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 18\n    },\n    __self: this\n  }, \"Server exceptions\"), __jsx(\"ul\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 19\n    },\n    __self: this\n  }, __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 20\n    },\n    __self: this\n  }, \"getInitialProps throws an Error. This should cause _error.js to render and record Error('Client Test 1') in Sentry.\", ' ', __jsx(\"a\", {\n    href: \"/server/test1\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 23\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 27\n    },\n    __self: this\n  }, \"getInitialProps returns a Promise that rejects. This should cause _error.js to render and record Error('Server Test 2') in Sentry.\", ' ', __jsx(\"a\", {\n    href: \"/server/test2\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 30\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 34\n    },\n    __self: this\n  }, \"getInitialProps calls a Promise that rejects, but does not handle the rejection or await its result (returning synchronously). Sentry should record Error('Server Test 3').\", ' ', __jsx(\"a\", {\n    href: \"/server/test3\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 38\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 42\n    },\n    __self: this\n  }, \"There is a top-of-module Promise that rejects, but its result is not awaited. Sentry should record Error('Server Test 4'). Note this will also be recorded on the client side, once the page is hydrated.\", ' ', __jsx(\"a\", {\n    href: \"/server/test4\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 46\n    },\n    __self: this\n  }, \"Open in a new tab\"))), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 52\n    },\n    __self: this\n  }, \"Client exceptions\"), __jsx(\"ul\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 53\n    },\n    __self: this\n  }, __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 54\n    },\n    __self: this\n  }, \"getInitialProps throws an Error. This should cause _error.js to render and record Error('Client Test 1') in Sentry. Note Sentry will double count this exception. Once from an unhandledrejection and again in _error.js. Could be a bug in Next.js or Sentry, requires more debugging.\", ' ', __jsx(Link, {\n    href: \"/client/test1\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 60\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 61\n    },\n    __self: this\n  }, \"Perform client side navigation\"))), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 64\n    },\n    __self: this\n  }, \"getInitialProps returns a Promise that rejects. This should cause _error.js to render and record Error('Client Test 2') in Sentry. As above, Sentry will double count this exception.\", ' ', __jsx(Link, {\n    href: \"/client/test2\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 68\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 69\n    },\n    __self: this\n  }, \"Perform client side navigation\"))), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 72\n    },\n    __self: this\n  }, \"getInitialProps calls a Promise that rejects, but does not handle the rejection or await its result (returning synchronously). Sentry should record Error('Client Test 3').\", ' ', __jsx(Link, {\n    href: \"/client/test3\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 76\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 77\n    },\n    __self: this\n  }, \"Perform client side navigation\"))), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 80\n    },\n    __self: this\n  }, \"There is a top-of-module Promise that rejects, but its result is not awaited. Sentry should record Error('Client Test 4').\", ' ', __jsx(Link, {\n    href: \"/client/test4\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 83\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 84\n    },\n    __self: this\n  }, \"Perform client side navigation\")), ' ', \"or\", ' ', __jsx(\"a\", {\n    href: \"/client/test4\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 87\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 91\n    },\n    __self: this\n  }, \"There is a top-of-module exception. _error.js should render and record ReferenceError('process is not defined') in Sentry.\", ' ', __jsx(Link, {\n    href: \"/client/test5\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 94\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 95\n    },\n    __self: this\n  }, \"Perform client side navigation\")), ' ', \"or\", ' ', __jsx(\"a\", {\n    href: \"/client/test5\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 98\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 102\n    },\n    __self: this\n  }, \"There is an exception during React lifecycle that is caught by Next.js's React Error Boundary. In this case, when the component mounts. This should cause _error.js to render and record Error('Client Test 6') in Sentry.\", ' ', __jsx(Link, {\n    href: \"/client/test6\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 107\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 108\n    },\n    __self: this\n  }, \"Perform client side navigation\")), ' ', \"or\", ' ', __jsx(\"a\", {\n    href: \"/client/test6\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 111\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 115\n    },\n    __self: this\n  }, \"There is an unhandled Promise rejection during React lifecycle. In this case, when the component mounts. Sentry should record Error('Client Test 7').\", ' ', __jsx(Link, {\n    href: \"/client/test7\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 119\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 120\n    },\n    __self: this\n  }, \"Perform client side navigation\")), ' ', \"or\", ' ', __jsx(\"a\", {\n    href: \"/client/test7\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 123\n    },\n    __self: this\n  }, \"Open in a new tab\")), __jsx(\"li\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 127\n    },\n    __self: this\n  }, \"An Error is thrown from an event handler. Sentry should record Error('Client Test 8').\", ' ', __jsx(Link, {\n    href: \"/client/test8\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 130\n    },\n    __self: this\n  }, __jsx(\"a\", {\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 131\n    },\n    __self: this\n  }, \"Perform client side navigation\")), ' ', \"or\", ' ', __jsx(\"a\", {\n    href: \"/client/test8\",\n    target: \"_blank\",\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 134\n    },\n    __self: this\n  }, \"Open in a new tab\")))));\n};\n\nexport default Home;","map":{"version":3,"sources":["/Users/luffyzhou/webfront/github/next-sentry-demo/pages/index.js"],"names":["Link","Home","maxWidth","margin"],"mappings":";;;AAAA,OAAOA,IAAP,MAAiB,WAAjB;;AAEA,IAAMC,IAAI,GAAG,SAAPA,IAAO;AAAA,SACX;AAAK,IAAA,KAAK,EAAE;AAAEC,MAAAA,QAAQ,EAAE,GAAZ;AAAiBC,MAAAA,MAAM,EAAE;AAAzB,KAAZ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,wBADF,EAEE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,uLAFF,EAOE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,kBADF,oJAGwC,GAHxC,EAIE;AAAG,IAAA,IAAI,EAAC,+CAAR;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,iBAJF,CAPF,EAaE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBADF,EAEE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,4HAE+C,GAF/C,EAGE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAHF,CADF,EAQE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,2IAEmE,GAFnE,EAGE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAHF,CARF,EAeE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,oLAGiC,GAHjC,EAIE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAJF,CAfF,EAuBE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,kNAGkE,GAHlE,EAIE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAJF,CAvBF,CAFF,EAmCE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAnCF,EAoCE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,gSAKa,GALb,EAME,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CANF,CADF,EAWE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,8LAGkD,GAHlD,EAIE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAJF,CAXF,EAmBE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,oLAGiC,GAHjC,EAIE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAJF,CAnBF,EA2BE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,mIAEwD,GAFxD,EAGE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAHF,EAKU,GALV,QAMK,GANL,EAOE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAPF,CA3BF,EAsCE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,mIAEsD,GAFtD,EAGE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAHF,EAKU,GALV,QAMK,GANL,EAOE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAPF,CAtCF,EAiDE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,mOAIsB,GAJtB,EAKE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CALF,EAOU,GAPV,QAQK,GARL,EASE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBATF,CAjDF,EA8DE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,8JAG0B,GAH1B,EAIE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAJF,EAMU,GANV,QAOK,GAPL,EAQE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBARF,CA9DF,EA0EE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,+FAE0B,GAF1B,EAGE,MAAC,IAAD;AAAM,IAAA,IAAI,EAAC,eAAX;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,KACE;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sCADF,CAHF,EAKU,GALV,QAMK,GANL,EAOE;AAAG,IAAA,IAAI,EAAC,eAAR;AAAwB,IAAA,MAAM,EAAC,QAA/B;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,yBAPF,CA1EF,CApCF,CAbF,CADW;AAAA,CAAb;;AA2IA,eAAeF,IAAf","sourcesContent":["import Link from 'next/link';\n\nconst Home = () => (\n  <div style={{ maxWidth: 700, margin: '0 auto' }}>\n    <h2>Next-Sentry-Demo</h2>\n    <p>\n      This example demonstrates how to record unhandled exceptions in your code\n      with Sentry. There are several test pages below that result in various\n      kinds of unhandled exceptions.\n    </p>\n    <p>\n      <strong>Important:</strong> exceptions in development mode take a\n      different path than in production. These tests should be run on a\n      production build (i.e. 'next build').{' '}\n      <a href=\"https://nextjs.org/docs#custom-error-handling\">Read more</a>\n    </p>\n    <ul>\n      <li>Server exceptions</li>\n      <ul>\n        <li>\n          getInitialProps throws an Error. This should cause _error.js to render\n          and record Error('Client Test 1') in Sentry.{' '}\n          <a href=\"/server/test1\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          getInitialProps returns a Promise that rejects. This should cause\n          _error.js to render and record Error('Server Test 2') in Sentry.{' '}\n          <a href=\"/server/test2\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          getInitialProps calls a Promise that rejects, but does not handle the\n          rejection or await its result (returning synchronously). Sentry should\n          record Error('Server Test 3').{' '}\n          <a href=\"/server/test3\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          There is a top-of-module Promise that rejects, but its result is not\n          awaited. Sentry should record Error('Server Test 4'). Note this will\n          also be recorded on the client side, once the page is hydrated.{' '}\n          <a href=\"/server/test4\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n      </ul>\n\n      <li>Client exceptions</li>\n      <ul>\n        <li>\n          getInitialProps throws an Error. This should cause _error.js to render\n          and record Error('Client Test 1') in Sentry. Note Sentry will double\n          count this exception. Once from an unhandledrejection and again in\n          _error.js. Could be a bug in Next.js or Sentry, requires more\n          debugging.{' '}\n          <Link href=\"/client/test1\">\n            <a>Perform client side navigation</a>\n          </Link>\n        </li>\n        <li>\n          getInitialProps returns a Promise that rejects. This should cause\n          _error.js to render and record Error('Client Test 2') in Sentry. As\n          above, Sentry will double count this exception.{' '}\n          <Link href=\"/client/test2\">\n            <a>Perform client side navigation</a>\n          </Link>\n        </li>\n        <li>\n          getInitialProps calls a Promise that rejects, but does not handle the\n          rejection or await its result (returning synchronously). Sentry should\n          record Error('Client Test 3').{' '}\n          <Link href=\"/client/test3\">\n            <a>Perform client side navigation</a>\n          </Link>\n        </li>\n        <li>\n          There is a top-of-module Promise that rejects, but its result is not\n          awaited. Sentry should record Error('Client Test 4').{' '}\n          <Link href=\"/client/test4\">\n            <a>Perform client side navigation</a>\n          </Link>{' '}\n          or{' '}\n          <a href=\"/client/test4\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          There is a top-of-module exception. _error.js should render and record\n          ReferenceError('process is not defined') in Sentry.{' '}\n          <Link href=\"/client/test5\">\n            <a>Perform client side navigation</a>\n          </Link>{' '}\n          or{' '}\n          <a href=\"/client/test5\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          There is an exception during React lifecycle that is caught by\n          Next.js's React Error Boundary. In this case, when the component\n          mounts. This should cause _error.js to render and record Error('Client\n          Test 6') in Sentry.{' '}\n          <Link href=\"/client/test6\">\n            <a>Perform client side navigation</a>\n          </Link>{' '}\n          or{' '}\n          <a href=\"/client/test6\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          There is an unhandled Promise rejection during React lifecycle. In\n          this case, when the component mounts. Sentry should record\n          Error('Client Test 7').{' '}\n          <Link href=\"/client/test7\">\n            <a>Perform client side navigation</a>\n          </Link>{' '}\n          or{' '}\n          <a href=\"/client/test7\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n        <li>\n          An Error is thrown from an event handler. Sentry should record\n          Error('Client Test 8').{' '}\n          <Link href=\"/client/test8\">\n            <a>Perform client side navigation</a>\n          </Link>{' '}\n          or{' '}\n          <a href=\"/client/test8\" target=\"_blank\">\n            Open in a new tab\n          </a>\n        </li>\n      </ul>\n    </ul>\n  </div>\n)\nexport default Home;"]},"metadata":{},"sourceType":"module"}